<?php
 return array (
  'email_whitelist_enable' => '0',
  'email_whitelist_suffix' => 
  array (
    0 => 'gmail.com',
    1 => 'qq.com',
    2 => '163.com',
    3 => 'yahoo.com',
    4 => 'sina.com',
    5 => '126.com',
    6 => 'outlook.com',
    7 => 'yeah.net',
    8 => 'foxmail.com',
  ),
  'email_gmail_limit_enable' => '1',
  'recaptcha_enable' => '0',
  'recaptcha_key' => NULL,
  'recaptcha_site_key' => NULL,
  'email_verify' => '0',
  'safe_mode_enable' => '0',
  'register_limit_by_ip_enable' => '0',
  'register_limit_count' => '3',
  'register_limit_expire' => '60',
  'secure_path' => 'RexLeeAdmin',
  'password_limit_enable' => '1',
  'password_limit_count' => '5',
  'password_limit_expire' => '60',
  'logo' => NULL,
  'force_https' => '1',
  'stop_register' => '1',
  'app_name' => 'RexCloud',
  'app_description' => 'AyanamiRei is best!',
  'app_url' => 'https://rexcloud.rexlee.click',
  'subscribe_url' => NULL,
  'try_out_plan_id' => '0',
  'try_out_hour' => '1',
  'tos_url' => NULL,
  'currency' => 'CNY',
  'currency_symbol' => '¥',
  'frontend_theme' => 'Bob-Theme-Argon',
  'frontend_theme_sidebar' => 'light',
  'frontend_theme_header' => 'dark',
  'frontend_theme_color' => 'default',
  'frontend_background_url' => 'https://raw.githubusercontent.com/Rex0929/Panel/main/43_Destination3_4k.PNG',
  'server_token' => 'AyanamiRei20010330RexLee',
  'server_pull_interval' => '60',
  'server_push_interval' => '60',
  'telegram_bot_enable' => '1',
  'telegram_bot_token' => '5740449201:AAEZKURZ1tH8JpykawokM_qZJhvVZdBrBBA',
  'telegram_discuss_link' => NULL,
) ;